# Generated by Django 4.2.20 on 2025-04-13 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('priority', models.IntegerField(default=0)),
                ('executed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor', to='core.task')),
                ('before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor', to='core.task')),
            ],
        ),
    ]
