# Generated by Django 4.2.20 on 2025-03-25 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_shipping_address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_query_name="user_info",
                to="Ecommerce.shippingaddress",
            ),
        ),
    ]
