# Generated by Django 4.2.20 on 2025-03-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CacheEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField()),
                ("frequency", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
